Add code for set EPS configuration parameter
davincisatellite/msp-flightsoftware pull request #38
Opened 2024-10-19 14:33 UTC by DavidGhergut

I have added the `set_config_params` function with comments! Solves issue #37

2024-10-19 15:29 UTC, mavaneerden requested changes

2024-10-19 15:29 UTC, mavaneerden commented on src/EPS.cpp
> +    wire.endTransmission();
Check error

2024-10-19 15:29 UTC, mavaneerden commented on src/EPS.cpp
> +    delay_ms(25);
is this delay really necessary? It isn't done anywhere else where we use I2C.

2024-10-19 15:29 UTC, mavaneerden commented on src/EPS.cpp
> +        wire.write(par_val[i]);
Check for nullptr first

2024-10-19 15:29 UTC, mavaneerden commented on src/EPS.cpp
> +        reply.error = 1;
Have more error codes than just 0 or 1. We need to determine what exactly goes wrong. Use a different code for different failure modes, and don't use magic numbers but use enum classes instead.

2024-10-19 15:29 UTC, mavaneerden commented on src/EPS.cpp
> +    wire.write(par_id >> 8);    // most significant byte of PAR_ID
I think this part is repeated in multiple other functions, perhaps you can isolate it so it can be reused without copy-paste.

2024-10-19 15:29 UTC, mavaneerden commented on src/EPS.cpp
> +    wire.write(0x00); // BID
Don't use magic numbers here.

2024-10-20 18:25 UTC, DavidGhergut commented on src/EPS.cpp
> +    wire.write(0x00); // BID
@mavaneerden I completely agree here! There is an issue regarding refactoring already up, see #34 where creating constants for these values is one of the refactoring points and it has been addressed in pull request #40 !

2024-10-21 14:37 UTC, mavaneerden requested changes

2024-10-21 14:37 UTC, mavaneerden commented on src/EPS.cpp
> +void writeCommand(Dwire &wire, uint8_t i2c_address, Identifiers stid, Identifiers ivid, CommandCode commandCode, Identifiers bid) {
STID, IVID and BID are always the same, I think you should remove these from the parameters

2024-10-21 14:37 UTC, mavaneerden commented on src/EPS.cpp
> +enum CommandCode {
If you use an `enum class` here, you don't need to prefix your enums with `CMD_CODE`, you can just use `Command::MY_COMMAND`

2024-10-21 14:37 UTC, mavaneerden commented on src/EPS.cpp
>  bool is_valid_param_id(uint16_t par_id) {
I think if you make Parameter IDs an enum class, you don't even need this validation function because it'll check if it is a Parameter ID instance at compile time. You should still keep the length check though, or alternatively make the compiler error when not all possible enum values have been used in a switch case

2024-10-21 14:37 UTC, mavaneerden commented on src/EPS.cpp
> +    wire.endTransmission();
Would be nice to add this piece to the wireCommand function, since it is used elsewhere as well

2024-10-21 18:41 UTC, DavidGhergut commented on src/EPS.cpp
> +    delay_ms(25);
![image](https://github.com/user-attachments/assets/294c9611-5148-4ed7-9461-9b63d358766c)

According to this screenshot from Matteo, the delay is necessary, however we are using 25 ms instead of 20 ms as mentioned, but I think we can tweak this value in testing as well!

2024-10-22 14:10 UTC, mavaneerden commented on src/EPS.h
> +    static config_reply set_config_params(DWire &wire, uint8_t i2c_address, uint16_t par_id, uint8_t *par_val);
Why are all the functions here static?

2024-11-01 14:50 UTC, ViciousDoormat commented on src/EPS.h
> +    static config_reply set_config_params(DWire &wire, uint8_t i2c_address, uint16_t par_id, uint8_t *par_val);
That's a great question I never actually asked haha. 
I think because the driver can be seen as something without a state, and I think there are multiple parts in the project that need access to it and this gives them easy access.
If you would make it a class, it would have to be a singleton (I think). You could argue this would be better, but due to the lack of state I do not think this is such a problem

2024-11-01 15:53 UTC, ViciousDoormat commented on src/EPS.cpp
>  bool is_valid_param_id(uint16_t par_id) {
Done

2024-11-01 15:56 UTC, ViciousDoormat commented on src/EPS.cpp
> +        reply.error = 1;
I agree that this has to be determined. However, I do not think this is relevant to this specific issue. I will make a new issue for it and link to it in this comment

#52

2024-11-01 16:59 UTC, ViciousDoormat commented on src/EPS.cpp
> +    wire.endTransmission();
What error?

2024-11-01 17:07 UTC, ViciousDoormat commented on src/EPS.cpp
> +        wire.write(par_val[i]);
Done

2024-11-01 17:10 UTC, ViciousDoormat commented on src/EPS.cpp
> +    wire.endTransmission();
First of all, after going through the code I could not find another part that does this as well. However, I think there will be added one additional command that will do it.
Second, how do you envision this? The command writes other stuff between that for loop and the write command, and most commands do not use this for loop.
Maybe it would be better to make it its own function

2024-11-01 19:59 UTC, ViciousDoormat commented
Currently, also with the ParameterID enum I introduced, we only capture the data types the paramteres can have. They are based on table 3-24 on page 77. However, the next table showcases all paramters, a lot more than we currently capture. They are categorized based on the data type codes in tabel 77 (all parameters that give a uint16 start with 0x4). We need to find a nice way to capture this complexity

2024-11-02 12:04 UTC, mavaneerden commented
> Currently, also with the ParameterID enum I introduced, we only capture the data types the paramteres can have. They are based on table 3-24 on page 77. However, the next table showcases all paramters, a lot more than we currently capture. They are categorized based on the data type codes in tabel 77 (all parameters that give a uint16 start with 0x4). We need to find a nice way to capture this complexity

That is because the ParameterID enum doesnt actually contain parameter IDs, but parameter types. These are separate things

2024-11-02 12:07 UTC, mavaneerden commented on src/EPS.cpp
> +    wire.endTransmission();
Endtransmission can return an error code, though you dont actually need to use it because requestFrom already does that for you. Difference is that endtransmission sends a stop signal, and requestfrom does not. So you have to check what you need here

2024-11-02 12:21 UTC, mavaneerden commented on src/EPS.cpp
> +    wire.endTransmission();
Yeah in hindsight, you can leave it like this

2024-11-02 12:23 UTC, mavaneerden commented on src/EPS.cpp
> +    delay_ms(25);
Okay, but it says here that you should probably check the CC/RC byte, and you are not doing that.

The fear I have is that you are blocking the entire OBC for 25ms. I am not sure how much of a problem that is, you should investigate.

2024-11-02 12:28 UTC, mavaneerden commented on src/EPS.h
> +    static config_reply set_config_params(DWire &wire, uint8_t i2c_address, uint16_t par_id, uint8_t *par_val);
Why is it stateless? Shouldnt it have a dedicated dwire and i2c bus as its state?
Because now you have to pass the same i2c address and dwire bus to the driver every time, which is tedious and error-prone

2024-11-02 13:19 UTC, ViciousDoormat commented
> > Currently, also with the ParameterID enum I introduced, we only capture the data types the paramteres can have. They are based on table 3-24 on page 77. However, the next table showcases all paramters, a lot more than we currently capture. They are categorized based on the data type codes in tabel 77 (all parameters that give a uint16 start with 0x4). We need to find a nice way to capture this complexity
> 
> That is because the ParameterID enum doesnt actually contain parameter IDs, but parameter types. These are separate things

Exactly, that is my point. But just making a huge enum is unwise I think, because parts are clearly grouped by type. I referred to this when I said we need a nice way to capture the complexity. 
Maybe the best solution would be an enum per type. However, then the parameter passed to the set conf param function would need to encompass all those enums. I think the union type we discussed during the meeting might be able to do that.

2024-11-02 13:22 UTC, ViciousDoormat commented on src/EPS.h
> +    static config_reply set_config_params(DWire &wire, uint8_t i2c_address, uint16_t par_id, uint8_t *par_val);
We can discuss this during next meeting. I think it is unwise to put effort into this refactoring for a state that would be that small

2024-11-02 13:26 UTC, ViciousDoormat commented on src/EPS.cpp
> +    delay_ms(25);
I agree, we should investigate this, but that can probably only be done later in the project right? When parts actually request things from the EPS. 
BTW, as far as I understood their advice of checking the CC/RC in scheme 1, they advise checking the value after the period of 20ms. So this would not solve the issue you mention. What would potentially solve it is choosing scheme 2

2024-11-04 13:13 UTC, mavaneerden commented on src/EPS.cpp
> +    delay_ms(25);
yes the checking is a separate problem. If you want to investigate the delay later, make sure you have documented this somewhere (in the code preferably, and maybe somewehere else too).

2024-11-04 13:15 UTC, mavaneerden commented
> > > Currently, also with the ParameterID enum I introduced, we only capture the data types the paramteres can have. They are based on table 3-24 on page 77. However, the next table showcases all paramters, a lot more than we currently capture. They are categorized based on the data type codes in tabel 77 (all parameters that give a uint16 start with 0x4). We need to find a nice way to capture this complexity
> > 
> > 
> > That is because the ParameterID enum doesnt actually contain parameter IDs, but parameter types. These are separate things
> 
> Exactly, that is my point. But just making a huge enum is unwise I think, because parts are clearly grouped by type. I referred to this when I said we need a nice way to capture the complexity. Maybe the best solution would be an enum per type. However, then the parameter passed to the set conf param function would need to encompass all those enums. I think the union type we discussed during the meeting might be able to do that.

I don't see why using a giant enum is problematic. You can put all parameters in there, this allows the higher layer to forget about the exact parameter code, and allows you to check valid IDs at compile time. As for checking the type, you mentioned that the parameter ID starts with a certain number, I think you can just check that number to find the type.

2024-11-04 14:34 UTC, ViciousDoormat commented
> > > > Currently, also with the ParameterID enum I introduced, we only capture the data types the paramteres can have. They are based on table 3-24 on page 77. However, the next table showcases all paramters, a lot more than we currently capture. They are categorized based on the data type codes in tabel 77 (all parameters that give a uint16 start with 0x4). We need to find a nice way to capture this complexity
> > > 
> > > 
> > > That is because the ParameterID enum doesnt actually contain parameter IDs, but parameter types. These are separate things
> > 
> > 
> > Exactly, that is my point. But just making a huge enum is unwise I think, because parts are clearly grouped by type. I referred to this when I said we need a nice way to capture the complexity. Maybe the best solution would be an enum per type. However, then the parameter passed to the set conf param function would need to encompass all those enums. I think the union type we discussed during the meeting might be able to do that.
> 
> I don't see why using a giant enum is problematic. You can put all parameters in there, this allows the higher layer to forget about the exact parameter code, and allows you to check valid IDs at compile time. As for checking the type, you mentioned that the parameter ID starts with a certain number, I think you can just check that number to find the type.

If we go for a giant enum, the functions calling the get/set-param commands do not have to explicitly use the type of the value they get/set. This seems very error-prone.

2024-11-07 17:58 UTC, mavaneerden commented
> > > > > Currently, also with the ParameterID enum I introduced, we only capture the data types the paramteres can have. They are based on table 3-24 on page 77. However, the next table showcases all paramters, a lot more than we currently capture. They are categorized based on the data type codes in tabel 77 (all parameters that give a uint16 start with 0x4). We need to find a nice way to capture this complexity
> > > > 
> > > > 
> > > > That is because the ParameterID enum doesnt actually contain parameter IDs, but parameter types. These are separate things
> > > 
> > > 
> > > Exactly, that is my point. But just making a huge enum is unwise I think, because parts are clearly grouped by type. I referred to this when I said we need a nice way to capture the complexity. Maybe the best solution would be an enum per type. However, then the parameter passed to the set conf param function would need to encompass all those enums. I think the union type we discussed during the meeting might be able to do that.
> > 
> > 
> > I don't see why using a giant enum is problematic. You can put all parameters in there, this allows the higher layer to forget about the exact parameter code, and allows you to check valid IDs at compile time. As for checking the type, you mentioned that the parameter ID starts with a certain number, I think you can just check that number to find the type.
> 
> If we go for a giant enum, the functions calling the get/set-param commands do not have to explicitly use the type of the value they get/set. This seems very error-prone.

That is true, but you need an ID *and* a value somehow, they can use separate structures I think. But I can't really think of a way to do that nicely.

2024-11-12 23:02 UTC, ViciousDoormat commented on src/EPS.cpp
> +    delay_ms(25);
Added the TODO to the code documentation

2025-01-15 18:02 UTC, DavidGhergut reviewed
I think we can merge now since we have a lot of changes for a single PR :)!

2025-02-07 11:10 UTC, merged