Fix bug 2, 3 and 4 and create constants for common values in the code
davincisatellite/msp-flightsoftware pull request #40
Opened 2024-10-20 18:21 UTC by DavidGhergut

Partially solves issues #33 and #34

2024-10-20 18:42 UTC, ViciousDoormat commented on src/EPS.cpp
> +const uint8_t STID = 0x00;
Mention this bypasses the STID check (page 17)

2024-10-20 18:43 UTC, ViciousDoormat commented on src/EPS.cpp
> +const uint8_t IVID = 0x06;
mention this is required according to page 19

2024-10-20 18:44 UTC, ViciousDoormat commented on src/EPS.cpp
> +const uint8_t BID = 0x00;
Mention this bypasses the BID (page 20)

2024-10-20 18:45 UTC, ViciousDoormat commented on src/EPS.cpp
> +    wire.write(STID); // STID
As the constants now capture what they mean, the comments are no longer needed. This also refers to all other lines

2024-10-20 21:16 UTC, mavaneerden requested changes

2024-10-20 21:16 UTC, mavaneerden commented on src/EPS.cpp
> +const uint8_t CONF_KEY_RESET_CONFIGURATION = 0xA7;              // reference: page 66 of 87 (ICD)
Use enums to categorize these constants.

2024-10-20 21:16 UTC, mavaneerden commented on src/EPS.cpp
> -        reply.stat = wire.read();  // Status byte
Why comments removed? I think they are valuable.

2024-10-20 21:25 UTC, ViciousDoormat commented on src/EPS.cpp
> -        reply.stat = wire.read();  // Status byte
These ones could still be somewhat valuable, but the variable names written to already cover them for the most part. In my opinion, the documentation of reply should cover the meaning of its variables (like stat = status code), not the comments in another code file.

2024-10-20 21:50 UTC, DavidGhergut commented on src/EPS.cpp
> -        reply.stat = wire.read();  // Status byte
I have readded them in the latest commit! Even though I can also argue they are quite redundant, maybe for a person that hasn't seen the code before, it is better to point out what every attribute means

2024-10-20 21:50 UTC, DavidGhergut commented on src/EPS.cpp
> +const uint8_t CONF_KEY_RESET_CONFIGURATION = 0xA7;              // reference: page 66 of 87 (ICD)
@mavaneerden It should be done in the last commits!

2024-10-20 21:56 UTC, ViciousDoormat commented on src/EPS.cpp
> +        reply.stid = wire.read();   // STID
This could also be made into a function to witch you pass "reply" right? As it is repeated multiple times

2024-10-20 21:59 UTC, DavidGhergut commented on src/EPS.cpp
> +        reply.stid = wire.read();   // STID
Yes, I will definitely do that in a bit!

2024-10-20 22:07 UTC, DavidGhergut commented on src/EPS.cpp
> +        reply.stid = wire.read();   // STID
Nevermind, I realized that I need to change a bit more if a want a function for the reply, thus I think I will do it tomorrow!

2024-10-21 10:27 UTC, merged

2024-10-21 11:09 UTC, ViciousDoormat commented
Standard reading logic has not yet been abstracted towards a function, but merging has been performed to already start adding functionality to refactored code.